---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: maven-app
  namespace: default
  labels:
    app: maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-app
  template:
    metadata:
      labels:
        app: maven-app
    spec:
      containers:
      - name: maven-app
        image: ashmit321/nodejsapp-1.0:latest
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: maven-app
  namespace: default
spec:
  selector:
    app: maven-app
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 3000
    nodePort: 31110
